Allow logging in using cloud variables
InternationalScratchWiki/mediawiki-scratch-login pull request #20
Opened 2021-06-24 19:44 UTC by apple502j

New settings: `$wgScratchLoginAuthenticator` which can be `project` (default) or `cloud`.

2021-06-24 19:49 UTC, ahmetlii commented on .editorconfig
> +insert_final_newline = true
It would be good to remove that file while committing, it's unnecessary

2021-06-25 16:57 UTC, jacob-g commented
```
[1bfae0e63936793b824e5fe3] /wiki/Special:ScratchLogin TypeError from line 17 of /var/www/html/w/extensions/mediawiki-scratch-login/authenticator/CloudVariableAuthenticator.php: random_int() expects parameter 1 to be int, float given

Backtrace:

#0 /var/www/html/w/extensions/mediawiki-scratch-login/authenticator/CloudVariableAuthenticator.php(17): random_int(double, integer)
#1 /var/www/html/w/extensions/mediawiki-scratch-login/authenticator/Authenticator.php(26): ScratchLogin\Authenticator\CloudVariableAuthenticator::generateRandomAuthCode()
#2 /var/www/html/w/extensions/mediawiki-scratch-login/authenticator/Authenticator.php(38): ScratchLogin\Authenticator\Authenticator::generateAndSetAuthCode(MediaWiki\Session\Session)
#3 /var/www/html/w/extensions/mediawiki-scratch-login/authenticator/CloudVariableAuthenticator.php(67): ScratchLogin\Authenticator\Authenticator::getOrCreateAuthCode(MediaWiki\Session\Session)
#4 /var/www/html/w/extensions/mediawiki-scratch-login/ScratchLogin.common.php(77): ScratchLogin\Authenticator\CloudVariableAuthenticator::getInstructions(string, MediaWiki\Session\Session, SpecialScratchLogin)
#5 /var/www/html/w/extensions/mediawiki-scratch-login/SpecialScratchLogin.php(15): ScratchSpecialPage->verifForm(OutputPage, WebRequest, string, string)
#6 /var/www/html/w/extensions/mediawiki-scratch-login/ScratchLogin.common.php(53): SpecialScratchLogin->showForm(OutputPage, WebRequest)
#7 /var/www/html/w/includes/specialpage/SpecialPage.php(600): ScratchSpecialPage->execute(NULL)
#8 /var/www/html/w/includes/specialpage/SpecialPageFactory.php(635): SpecialPage->run(NULL)
#9 /var/www/html/w/includes/MediaWiki.php(307): MediaWiki\SpecialPage\SpecialPageFactory->executePath(Title, RequestContext)
#10 /var/www/html/w/includes/MediaWiki.php(940): MediaWiki->performRequest()
#11 /var/www/html/w/includes/MediaWiki.php(543): MediaWiki->main()
#12 /var/www/html/w/index.php(53): MediaWiki->run()
#13 /var/www/html/w/index.php(46): wfIndexMain()
#14 {main}
```

2021-06-25 17:04 UTC, jacob-g requested changes
This breaks right out of the gate because of the way verification codes are generated.

2021-06-25 17:04 UTC, jacob-g commented on ScratchLogin.common.php
> +        $authenticator = getAuthenticator();
indentation

2021-06-25 17:04 UTC, jacob-g commented on ScratchLogin.common.php
> +        $authenticator = getAuthenticator();
indentation again

2021-06-25 17:04 UTC, jacob-g commented on i18n/en.json
> +    "scratchlogin-cloud-project-id": "548006054",
...indentation...

2021-06-25 17:04 UTC, jacob-g commented on authenticator/Authenticator.php
> +abstract class Authenticator {
Nice use of inheritance and polymorphism, though one question I do have is whether or not the logic related to generating random codes should be done in the base class since it's possible someday someone might come up with something that doesn't involve using random codes.

2021-06-25 17:04 UTC, jacob-g commented on authenticator/CloudVariableAuthenticator.php
> +        $a = random_int(1e18, PHP_INT_MAX);
There is no actual guarantee that `PHP_INT_MAX` won't someday grow large enough that this will blow out the cloud data limit. A better approach may be to start with a digit from 1-9 and then just concatenate random digits onto it until we get to the length we want.

2021-06-25 17:04 UTC, jacob-g commented on authenticator/CloudVariableAuthenticator.php
> +		$a = random_int(1e18, PHP_INT_MAX);
This fails with the following error:
```
[1bfae0e63936793b824e5fe3] /wiki/Special:ScratchLogin TypeError from line 17 of /var/www/html/w/extensions/mediawiki-scratch-login/authenticator/CloudVariableAuthenticator.php: random_int() expects parameter 1 to be int, float given

Backtrace:

#0 /var/www/html/w/extensions/mediawiki-scratch-login/authenticator/CloudVariableAuthenticator.php(17): random_int(double, integer)
#1 /var/www/html/w/extensions/mediawiki-scratch-login/authenticator/Authenticator.php(26): ScratchLogin\Authenticator\CloudVariableAuthenticator::generateRandomAuthCode()
#2 /var/www/html/w/extensions/mediawiki-scratch-login/authenticator/Authenticator.php(38): ScratchLogin\Authenticator\Authenticator::generateAndSetAuthCode(MediaWiki\Session\Session)
#3 /var/www/html/w/extensions/mediawiki-scratch-login/authenticator/CloudVariableAuthenticator.php(67): ScratchLogin\Authenticator\Authenticator::getOrCreateAuthCode(MediaWiki\Session\Session)
#4 /var/www/html/w/extensions/mediawiki-scratch-login/ScratchLogin.common.php(77): ScratchLogin\Authenticator\CloudVariableAuthenticator::getInstructions(string, MediaWiki\Session\Session, SpecialScratchLogin)
#5 /var/www/html/w/extensions/mediawiki-scratch-login/SpecialScratchLogin.php(15): ScratchSpecialPage->verifForm(OutputPage, WebRequest, string, string)
#6 /var/www/html/w/extensions/mediawiki-scratch-login/ScratchLogin.common.php(53): SpecialScratchLogin->showForm(OutputPage, WebRequest)
#7 /var/www/html/w/includes/specialpage/SpecialPage.php(600): ScratchSpecialPage->execute(NULL)
#8 /var/www/html/w/includes/specialpage/SpecialPageFactory.php(635): SpecialPage->run(NULL)
#9 /var/www/html/w/includes/MediaWiki.php(307): MediaWiki\SpecialPage\SpecialPageFactory->executePath(Title, RequestContext)
#10 /var/www/html/w/includes/MediaWiki.php(940): MediaWiki->performRequest()
#11 /var/www/html/w/includes/MediaWiki.php(543): MediaWiki->main()
#12 /var/www/html/w/index.php(53): MediaWiki->run()
#13 /var/www/html/w/index.php(46): wfIndexMain()
#14 {main}
```

A better idea might be to instead just start with a random int from 1 to 9 and then repeatedly concatenate ints from 0 to 9 until it's the desired length.

2021-06-25 17:32 UTC, apple502j commented on authenticator/Authenticator.php
> +abstract class Authenticator {
Not sure if that'll happen, so i'll keep for now.

2021-07-02 02:00 UTC, jacob-g approved these changes
Looks good. Sorry for procrastinating on reviewing this.

2021-07-02 02:01 UTC, merged