Update Japanese i18n
InternationalScratchWiki/mediawiki-scratch-login pull request #4
Opened 2020-08-12 05:20 UTC by apple502j

2020-08-12 05:29 UTC, Kenny2github requested changes
A few mistakes need correcting

2020-08-12 05:29 UTC, Kenny2github commented on i18n/ja.json
>  	"scratchlogin-instructions": "'''注意: Scratchでログインするには、このWikiにてすでにアカウントを持っていないといけません!'''<br/>以下の認証コードを$1認証用プロジェクト$2のコメント欄にコメントしてください。<br/>'''$3'''<br/><small>(必要な場合は、[[Special:ScratchLogin/reset|認証コー
```suggestion
	"scratchlogin-instructions": "'''注意: Scratchでログインするには、このWikiにてすでにアカウントを持っていないといけません!'''<br/>以下の認証コードを$1認証用プロジェクト$2のコメント欄にコメントしてください。<br/>'''$3'''<br/><small>(必要な場合は、[[Special:ScratchLogin/reset|認証コードをリセットできます]]。)</small>",
```

2020-08-12 05:29 UTC, Kenny2github commented on i18n/ja.json
>  	"scratchlogin-code-reset": "認証コードはリセットされました。<br/>[[Special:ScratchLogin]]へ戻る。",
```suggestion
	"scratchlogin-code-reset": "認証コードはリセットされました。<br/>[[$1]]へ戻る。",
```

2020-08-12 05:29 UTC, Kenny2github commented on i18n/ja.json
> +	"scratchlogin-instructions": "以下の認証コードを$1認証用プロジェクト$2のコメント欄にコメントしてください。<br/>'''$3'''<br/><small>(必要な場合は、[[Special:ScratchLogin/reset|認証コードをリセットできます]]。)",
```suggestion
	"scratchpasswordreset-instructions": "以下の認証コードを$1認証用プロジェクト$2のコメント欄にコメントしてください。<br/>'''$3'''<br/><small>(必要な場合は、[[Special:ScratchLogin/reset|認証コードをリセットできます]]。)</small>",
```

2020-08-15 09:52 UTC, Kenny2github commented
@apple502j any updates?

2020-08-19 07:36 UTC, T-taku commented
I can fix they.
Can I help you?

2020-08-19 09:35 UTC, Kenny2github approved these changes

2020-08-19 09:35 UTC, merged